<a href="https://colab.research.google.com/github/DataMind-Society/Meeting-2--Data-Analysis-with-Python/blob/main/Session2_Notes2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

Ww have collected our **OWN** data.
Start by importing this data and reading it with the help of the Pandas library.
In google colab, you have to press the "files" button and the "upload to session storage" button to import a file of you choice like a ".csv" file.

# read_csv()

In [ ]:
df = pd.read_csv('Form.csv')
#or df = pd.read_csv(r"D:\DataMind\Form.csv") #using the r string
#or df = pd.read_csv("D:/DataMind/Form.csv") where the \ becomes /

# head()

It is used to display the first rows of a DataFrame.

In [ ]:
df.head()

,Timestamp,Year of Study,Major,Favorite Programming Language,Are you familiar with Machine Learning?,"If so, for what have you used it?",Which of the following do you think uses Machine Learning?,Which Chatbot do you use?
0,2/14/2026 22:23:29,L3,CS,C++,NaN,NaN,Netflix movie recommendations,"ChatGPT, Copilot, Gemini"
1,2/14/2026 22:23:38,L2,CS,NaN,NaN,Natural Language Processing,Self-driving cars,"Claude, ChatGPT, Deepseek"
2,2/14/2026 22:23:45,L2,Physics,Matlab,NaN,"Prediction, Computer Vision",Google search,ChatGPT
3,2/14/2026 22:25:33,L1,CS,Python,NaN,NaN,Netflix movie recommendations,"ChatGPT, Deepseek"
4,2/15/2026 21:11:47,L3,CS,Python,Beginner,ai,Self-driving cars,"Claude, ChatGPT, Deepseek, Gemini"

In [ ]:
df.isna().sum()

Timestamp                                                      0
Year of Study                                                  0
Major                                                          0
Favorite Programming Language                                  1
Are you familiar with Machine Learning?                       11
If so, for what have you used it?                             11
Which of the following do you think uses Machine Learning?     0
Which Chatbot do you use?                                      0
dtype: int64

We see that we have NaN (empty data) in our dataset. In Pandas, NaN stands for “Not a Number” and represents missing or undefined values in the data.

Missing data can cause problems during analysis or visualization, so we often need to handle these values before continuing our analysis.

There are two common ways to deal with missing values:

# 1) Removing Missing Values

We can remove rows that contain missing values using the **dropna()** function

In [ ]:
df_cleaned1 = df.dropna()
df_cleaned1

,Timestamp,Year of Study,Major,Favorite Programming Language,Are you familiar with Machine Learning?,"If so, for what have you used it?",Which of the following do you think uses Machine Learning?,Which Chatbot do you use?
4,2/15/2026 21:11:47,L3,CS,Python,Beginner,ai,Self-driving cars,"Claude, ChatGPT, Deepseek, Gemini"
5,2/15/2026 21:11:55,L2,CS,C++,Beginner,Computer Vision,Weather forecasting,ChatGPT
6,2/15/2026 21:24:43,L3,CS,C,Beginner,Prediction,Email spam filtering,Deepseek
10,2/16/2026 20:26:43,L3,Physics,Python,Beginner,"Prediction, Recommendation",Self-driving cars,ChatGPT

# 2) Filling Missing Values

Instead of removing data, we can replace missing values with another value using the **fillna()** function.

a) Fill with zero

In [ ]:
df_cleaned2 = df.fillna(0) #FILL WITH NUMBER INSIDE
df_cleaned2

,Timestamp,Year of Study,Major,Favorite Programming Language,Are you familiar with Machine Learning?,"If so, for what have you used it?",Which of the following do you think uses Machine Learning?,Which Chatbot do you use?
0,2/14/2026 22:23:29,L3,CS,C++,0,0,Netflix movie recommendations,"ChatGPT, Copilot, Gemini"
1,2/14/2026 22:23:38,L2,CS,0,0,Natural Language Processing,Self-driving cars,"Claude, ChatGPT, Deepseek"
2,2/14/2026 22:23:45,L2,Physics,Matlab,0,"Prediction, Computer Vision",Google search,ChatGPT
3,2/14/2026 22:25:33,L1,CS,Python,0,0,Netflix movie recommendations,"ChatGPT, Deepseek"
4,2/15/2026 21:11:47,L3,CS,Python,Beginner,ai,Self-driving cars,"Claude, ChatGPT, Deepseek, Gemini"
5,2/15/2026 21:11:55,L2,CS,C++,Beginner,Computer Vision,Weather forecasting,ChatGPT
6,2/15/2026 21:24:43,L3,CS,C,Beginner,Prediction,Email spam filtering,Deepseek
7,2/16/2026 0:33:51,L3,CS,Java,0,0,Self-driving cars,ChatGPT
8,2/16/2026 7:15:06,L1,CS,C,0,0,Self-driving cars,Deepseek
9,2/16/2026 7:15:38,L1,CS,Python,Beginner,0,Google search,ChatGPT
10,2/16/2026 20:26:43,L3,Physics,Python,Beginner,"Prediction, Recommendation",Self-driving cars,ChatGPT
11,2/26/2026 19:03:19,M1,Physics,Python,0,0,Netflix movie recommendations,Gemini
12,2/26/2026 19:08:29,L1,CS,C,Beginner,0,Netflix movie recommendations,Gemini
13,2/26/2026 19:08:57,L2,CS,C++,0,0,Self-driving cars,"Claude, ChatGPT, Deepseek, Copilot, Gemini"
14,2/26/2026 19:37:20,L3,CS,Python,0,0,Self-driving cars,ChatGPT
15,2/26/2026 19:49:08,M1,Chemistry,Python,0,0,Self-driving cars,ChatGPT
16,2/26/2026 21:58:01,L2,Physics,Matlab,0,0,Google search,ChatGPT

Let us create a DataFrame that includes numbers as data.

b) Fill with mean value

In [ ]:
data = {
    "Day": ["Mon", "Tue", "Wed", "Thu", "Fri"],
    "Sales": [200, 250, 180, 300, 280],
    "Expenses": [150, 180, None, 200, 190]
}

df1 = pd.DataFrame(data)
df1

   Day  Sales  Expenses
0  Mon    200     150.0
1  Tue    250     180.0
2  Wed    180       NaN
3  Thu    300     200.0
4  Fri    280     190.0

In [ ]:
df1 = df1.fillna(df1["Expenses"].mean())
df1

   Day  Sales  Expenses
0  Mon    200     150.0
1  Tue    250     180.0
2  Wed    180     180.0
3  Thu    300     200.0
4  Fri    280     190.0

# **describe()**

generates descriptive statistics that summarize the central tendency, dispersion, and shape of a dataset's distribution

In [ ]:
df.describe()

,Timestamp,Year of Study,Major,Favorite Programming Language,Are you familiar with Machine Learning?,"If so, for what have you used it?",Which of the following do you think uses Machine Learning?,Which Chatbot do you use?
count,17,17,17,16,6,6,17,17
unique,17,4,3,5,1,6,5,8
top,2/14/2026 22:23:29,L3,CS,Python,Beginner,Natural Language Processing,Self-driving cars,ChatGPT
freq,1,6,12,7,6,1,8,8

In [ ]:
df1.describe()

            Sales    Expenses
count    5.000000    5.000000
mean   242.000000  180.000000
std     51.185936   18.708287
min    180.000000  150.000000
25%    200.000000  180.000000
50%    250.000000  180.000000
75%    280.000000  190.000000
max    300.000000  200.000000

# **info()**
gives a summary of our DataFrame.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 8 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Timestamp                                                   17 non-null     object
 1   Year of Study                                               17 non-null     object
 2   Major                                                       17 non-null     object
 3   Favorite Programming Language                               16 non-null     object
 4   Are you familiar with Machine Learning?                     6 non-null      object
 5   If so, for what have you used it?                           6 non-null      object
 6   Which of the following do you think uses Machine Learning?  17 non-null     object
 7   Which Chatbot do you use?                                   17 non-null     object
dtypes: object(8)
memory usage: 1.2+ KB

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Day       5 non-null      object
 1   Sales     5 non-null      int64
 2   Expenses  4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes